[package]
name = "lv-storage-sqlite"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
lv-core = { path = "../lv-core" }
lv-storage = { path = "../lv-storage" }
uuid = { workspace = true }
time = { workspace = true }
sqlx = { workspace = true }
async-trait = { workspace = true }
