[package]
name = "lv-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "lorevault"
path = "src/main.rs"

[dependencies]
lv-core = { path = "../lv-core" }
lv-auth = { path = "../lv-auth" }
lv-storage = { path = "../lv-storage" }
lv-gateway = { path = "../lv-gateway" }
tokio        = { workspace = true }
object_store = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
hyper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
config = { workspace = true }
sqlx = { workspace = true }
deadpool-redis = { workspace = true }
anyhow = { workspace = true }
