syntax = "proto3";

import "google/protobuf/timestamp.proto";

package urc.lock;

message Resource {
  bytes branch = 1;
  bytes hash = 2;
  string description = 3;
}

message Lock {
  Resource resource = 1;
  string owner = 2;
  google.protobuf.Timestamp locked_at = 3;
}

service LockService {
  rpc Lock(LockRequest) returns (LockResponse);
  rpc Query(QueryRequest) returns (QueryResponse);
  rpc Status(StatusRequest) returns (StatusResponse);
  rpc Unlock(UnlockRequest) returns (UnlockResponse);
  rpc AdminLock(AdminLockRequest) returns (AdminLockResponse);
}

message LockRequest { repeated Resource resources = 1; }
message LockResponse { repeated Lock locks = 1; }

message QueryRequest {
  optional bytes branch = 1;
  optional string owner = 2;
  optional string description = 3;
}
message QueryResponse { repeated Lock result = 1; }

message StatusRequest { repeated Resource resources = 1; }
message StatusResponse { repeated Lock locks = 1; }

message UnlockRequest { repeated Resource resources = 1; }
message UnlockResponse { repeated Resource resources = 1; }

message AdminLockRequest {
  repeated Resource resources = 1;
  string owner = 2;
}
message AdminLockResponse { repeated Lock locks = 1; }
