syntax = "proto3";

package lore.repository.v1;

import "lore/model/v1/model.proto";

service RepositoryService {
  rpc RepositoryCreate (RepositoryCreateRequest) returns (RepositoryCreateResponse);
  rpc RepositoryDelete (RepositoryDeleteRequest) returns (RepositoryDeleteResponse);
  rpc RepositoryGet (RepositoryGetRequest) returns (RepositoryGetResponse);
  rpc RepositoryList (RepositoryListRequest) returns (stream RepositoryListResponse);
  rpc RepositoryMetadataGet(RepositoryMetadataGetRequest) returns (RepositoryMetadataGetResponse);
  rpc RepositoryMetadataSet(RepositoryMetadataSetRequest) returns (RepositoryMetadataSetResponse);
}

message RepositoryCreateRequest {
  bytes id = 1;
  string name = 2;
  string description = 3;
  bytes default_branch_id = 4;
  string default_branch_name = 5;
  optional string creator = 6;
}

message RepositoryCreateResponse {
  lore.model.v1.Repository repository = 1;
}

message RepositoryDeleteRequest {
  bytes id = 1;
}

message RepositoryDeleteResponse {
  lore.model.v1.Repository repository = 1;
}

message RepositoryGetRequest {
  oneof query {
    bytes id = 1;
    string name = 2;
  }
}

message RepositoryGetResponse {
  lore.model.v1.Repository repository = 1;
}

message RepositoryListRequest {
  optional string creator = 1;
}

message RepositoryListResponse {
  lore.model.v1.Repository repository = 1;
}

message RepositoryMetadataGetRequest {
  bytes id = 1;
}

message RepositoryMetadataGetResponse {
  bytes metadata = 1;
}

message RepositoryMetadataSetRequest {
  bytes id = 1;
  bytes expected = 2;
  bytes updated = 3;
}

message RepositoryMetadataSetResponse {
  bytes metadata = 1;
}
