syntax = "proto3";

package lore.revision.v1;

import "lore/model/v1/model.proto";

service RevisionService {
  rpc BranchCreate (BranchCreateRequest) returns (BranchCreateResponse);
  rpc BranchDelete (BranchDeleteRequest) returns (BranchDeleteResponse);
  rpc BranchGet (BranchGetRequest) returns (BranchGetResponse);
  rpc BranchList (BranchListRequest) returns (stream BranchListResponse);
  rpc BranchPush (BranchPushRequest) returns (BranchPushResponse);
  rpc BranchMetadataGet(BranchMetadataGetRequest) returns (BranchMetadataGetResponse);
  rpc BranchMetadataSet(BranchMetadataSetRequest) returns (BranchMetadataSetResponse);
  rpc RevisionList (RevisionListRequest) returns (RevisionListResponse);
}

message BranchCreateRequest {
  bytes id = 1;
  string name = 2;
  optional string creator = 3;
  string category = 4;
  repeated lore.model.v1.BranchPoint stack = 5;
}

message BranchCreateResponse {
  lore.model.v1.Branch branch = 1;
}

message BranchDeleteRequest {
  bytes id = 1;
}

message BranchDeleteResponse {
  lore.model.v1.Branch branch = 1;
}

message BranchGetRequest {
  oneof query {
    bytes id = 1;
    string name = 2;
  }
}

message BranchGetResponse {
  lore.model.v1.Branch branch = 1;
}

message BranchListRequest {
  optional string creator = 1;
  bool include_deleted = 2;
}

message BranchListResponse {
  lore.model.v1.Branch branch = 1;
}

message BranchPushRequest {
  bytes id = 1;
  bytes revision_signature = 2;
  bool force = 3;
  bool fast_forward_merge = 4;
}

message BranchPushResponse {
  bytes revision_signature = 1;
  uint64 revision_number = 2;
  bool fast_forward_merged = 3;
  optional string message = 4;
}

message BranchMetadataGetRequest {
  bytes id = 1;
}

message BranchMetadataGetResponse {
  bytes metadata = 1;
}

message BranchMetadataSetRequest {
  bytes id = 1;
  bytes expected = 2;
  bytes updated = 3;
}

message BranchMetadataSetResponse {
  bytes metadata = 1;
}

message RevisionListRequest {
  oneof start {
    lore.model.v1.RevisionIdentifier identifier = 1;
    bytes signature = 2;
  }
}

message RevisionListResponse {
  repeated lore.model.v1.RevisionItem items = 1;
  optional bytes signature_forward = 2;
  optional bytes signature_backward = 3;
}
